# Code Generated by Sidekick is for learning and experimentation purposes only.
from flask import Flask, render_template, request, redirect, url_for, send_file
import sqlite3
import pandas as pd
import io

app = Flask(__name__)

def get_db_connection():
    conn = sqlite3.connect('C:/Users/tdhamodaran/sqliteDB/Retex.DB')
    conn.row_factory = sqlite3.Row
    return conn

@app.route('/')
def index():
    conn = get_db_connection()
    data = conn.execute('SELECT * FROM product').fetchall()
    conn.close()
    return render_template('index.html', data=data)

@app.route('/export')
def export_data():
    conn = get_db_connection()
    data = conn.execute('SELECT * FROM product').fetchall()
    conn.close()

    # Convert data to DataFrame
    df = pd.DataFrame(data)

    # Use a BytesIO buffer to create the Excel file in memory
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Sheet1')

    # Rewind the buffer
    output.seek(0)

    # Send the file to the user
    return send_file(output, as_attachment=True, download_name='data_export.xlsx', mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

if __name__ == '__main__':
    app.run(debug=True)
